name: fittrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.4.0
  http: ^1.4.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.15.8
  flutter_ringtone_player: ^4.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/onboarting_screen_background.jpg
    - assets/Images/2.jpg