// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4oQ63Fx03Ig6S_J4P_lMAJqkkYV75Qvo',
    appId: '1:696392235041:web:a77cb1543683bebdd4cb60',
    messagingSenderId: '696392235041',
    projectId: 'fittrackapp-7facf',
    authDomain: 'fittrackapp-7facf.firebaseapp.com',
    storageBucket: 'fittrackapp-7facf.firebasestorage.app',
    measurementId: 'G-S0166TWRM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaQGk_VNLMkHotp55YuHc1vYAzIHr8enM',
    appId: '1:696392235041:android:ca324c6b59de2ab3d4cb60',
    messagingSenderId: '696392235041',
    projectId: 'fittrackapp-7facf',
    storageBucket: 'fittrackapp-7facf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpN2hBsoCfAWlQvbqj9npBWcwVbQYR_a4',
    appId: '1:696392235041:ios:4b50b446a2800a7ad4cb60',
    messagingSenderId: '696392235041',
    projectId: 'fittrackapp-7facf',
    storageBucket: 'fittrackapp-7facf.firebasestorage.app',
    iosBundleId: 'com.example.fittrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpN2hBsoCfAWlQvbqj9npBWcwVbQYR_a4',
    appId: '1:696392235041:ios:4b50b446a2800a7ad4cb60',
    messagingSenderId: '696392235041',
    projectId: 'fittrackapp-7facf',
    storageBucket: 'fittrackapp-7facf.firebasestorage.app',
    iosBundleId: 'com.example.fittrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4oQ63Fx03Ig6S_J4P_lMAJqkkYV75Qvo',
    appId: '1:696392235041:web:efd26a22f2f205f7d4cb60',
    messagingSenderId: '696392235041',
    projectId: 'fittrackapp-7facf',
    authDomain: 'fittrackapp-7facf.firebaseapp.com',
    storageBucket: 'fittrackapp-7facf.firebasestorage.app',
    measurementId: 'G-0SV6CBH0C7',
  );
}
